### PR TITLE
BaSP-TG-41: Admins - Redux 

### PR DESCRIPTION
**Pull request by TomasBettini**

### CODE REVIEW

**Review by juliancit0 — APPROVED** [review]
Excellent

**Review by JuliBalcaza — APPROVED** [review]
Great Job Tomi

**Comment by JuliBalcaza** [comment]
approved by QA, as a suggestion remember to add a message to the list when it is empty ("Empty list" or "No Admins Yet").

**Review by JuliBalcaza — APPROVED** [review]
excellent!

**Review by juliancit0 — APPROVED** [review]

**Pull request merged**
