### PR TITLE
TG-21-27: table structure creation & implementation

### PR DESCRIPTION
**Pull request by mgriolfo-g**
Table implementations on all page components. Delete elements from Actions row not working, probably because of semantic differences in code!

### CODE REVIEW

**Comment by mgriolfo-g** [comment]
Fixed errors and proven work for different types of components (employees, projects and timesheets).
Delete buttons NOT working on most components, modal interaction has to be checked with @TomasBettini!

**Comment by mgriolfo-g** [comment]
Finished implementations on remaining components. Delete elements from Actions row not working, probably because of semantic differences in code!

**Review by leimeter-joaquin — CHANGES_REQUESTED** [review]
Delete button is not working for every entity, check that please

**Comment by mgriolfo-g** [comment]
> Delete button is not working for every entity, check that please

Solved, fixing it in every entity in cooperation with colleagues!

**Review by leimeter-joaquin — APPROVED** [review]

**Review by TomasBettini — APPROVED** [review]
Good job

**Pull request merged**
