### PR TITLE
BaSP-TG-28: Buttons Implementations (WIP)

### PR DESCRIPTION
**Pull request by juliancit0**
In this PR I implemented the buttons in the form, the table and the modal.

### CODE REVIEW

**Comment by juliancit0** [comment]
I'm waiting for the table component creation to implement the buttons to it

**Review by pabloschivazappa — APPROVED** [review]
Nice work!

**Review by mgriolfo-g — APPROVED** [review]
Way to go 🚀

**Comment by disimoneleandro** [comment]
Approved!

**Pull request merged**
